[package]
name = "tulip-solana-security-txt"
version = "0.1.0"
edition = "2021"
description = "fork of solana-security-txt"
readme = "../README.md"
license = "MIT OR Apache-2.0"


[dependencies]
thiserror = "1.0.30"
twoway = "0.2.2"
